### ISSUE TITLE
Password login

### ISSUE THREAD

**Issue by japemete** [fauzan1892/crud-php-generator#1]
Bro terimakasih atas kodenya yang akan membantu pembelajaran saya. Tapi untuk login kodenya apa bro? Boleh dong saya minta ke alamat email fahmi.nsk@gmail.com

**Comment by fauzan1892** [comment]
iya mas untuk login itu :
user : adminweb
pass : 123

**Comment by japemete** [comment]
Wah makasih ya langsung dijawab. Aku surprise. Semoga berkah buat Anda yang
telah berbagi ilmu.

Pada tanggal Sab, 27 Nov 2021 20.39, Fauzan Falah ***@***.***>
menulis:
